export enum RoomType {
  LIVING_ROOM = 'LIVING_ROOM',
  BEDROOM = 'BEDROOM',
  KITCHEN = 'KITCHEN',
  BATHROOM = 'BATHROOM',
  DINING_ROOM = 'DINING_ROOM',
  OFFICE = 'OFFICE',
  HALLWAY = 'HALLWAY',
  BALCONY = 'BALCONY',
  GARAGE = 'GARAGE',
  LAUNDRY = 'LAUNDRY',
  CLOSET = 'CLOSET',
  OTHER = 'OTHER',
}

export enum PropertyStatus {
  DRAFT = 'DRAFT',
  CAPTURING = 'CAPTURING',
  PROCESSING = 'PROCESSING',
  READY = 'READY',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
}

export enum MediaType {
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
  PANORAMA = 'PANORAMA',
}

export enum JobStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum JobType {
  ROOM_CLASSIFY = 'ROOM_CLASSIFY',
  ROOM_ORDER = 'ROOM_ORDER',
  FLOORPLAN_GENERATE = 'FLOORPLAN_GENERATE',
  TOUR_GENERATE = 'TOUR_GENERATE',
}
